/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rs_fncore_UrovoUtils */

#ifndef _Included_rs_fncore_UrovoUtils
#define _Included_rs_fncore_UrovoUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef rs_fncore_UrovoUtils_DM_unknown
#define rs_fncore_UrovoUtils_DM_unknown 0L
#undef rs_fncore_UrovoUtils_DM_SQ29
#define rs_fncore_UrovoUtils_DM_SQ29 1L
#undef rs_fncore_UrovoUtils_DM_SQ27T
#define rs_fncore_UrovoUtils_DM_SQ27T 2L
#undef rs_fncore_UrovoUtils_DM_SQ27TGW
#define rs_fncore_UrovoUtils_DM_SQ27TGW 3L
/*
 * Class:     rs_fncore_UrovoUtils
 * Method:    enableOtg
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_rs_fncore_UrovoUtils_enableOtg
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     rs_fncore_UrovoUtils
 * Method:    getOtgStatus
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_rs_fncore_UrovoUtils_getOtgStatus
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
