package rs.fncore2.io.one_c;

enum FNcoreActions {
    ACTION_GET_KKT_INFO,
    ACTION_REGISTER_KKT,
    ACTION_CHANGE_KKT_SETTINGS,
    ACTION_ARCHIVE_KKT,
    ACTION_OPEN_SHIFT,
    ACTION_CLOSE_SHIFT,
    ACTION_DO_CHECK_PRINT,
    ACTION_DO_CHECK,
    ACTION_DO_REPORT,
    ACTION_DO_CASH,
    ACTION_DO_X_REPORT,
    ACTION_DO_CHECK_COPY,
    ACTION_GET_STATUS,
    ACTION_DO_CORRECTION,
    ACTION_DO_PRINT,
    ACTION_DO_TEST,
    ACTION_PRINT_AGAIN,
    ACTION_OPEN_SESSION_REGISTRATION_KMN,
    ACTION_CLOSE_SESSION_REGISTRATION_KMN,
    ACTION_REQUEST_KM,
    ACTION_GET_PROCESSING_KM_RESULT,
    ACTION_CONFIRM_KM
}
