/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rs_fncore2_io_SAStorage */

#ifndef _Included_rs_fncore2_UrovoUtils
#define _Included_rs_fncore2_UrovoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
* Class:     Java_rs_fncore2_UrovoUtils
*/
JNIEXPORT jboolean JNICALL
Java_rs_fncore2_utils_UrovoUtils_getOtgStatus(JNIEnv *env, jclass clazz, jint deviceModel);
/*
 * Class:     Java_rs_fncore2_UrovoUtils
 */
JNIEXPORT jboolean JNICALL
Java_rs_fncore2_utils_UrovoUtils_enableOtg(JNIEnv *env, jclass clazz, jint deviceModel, jboolean enable);

#ifdef __cplusplus
}
#endif
#endif
